---
# file: roles/haproxy/tasks/main.yml

- name: Install haproxy
  yum: name=haproxy state=present

- name: Copy haproxy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Run an enable haproxy
  service: name=haproxy state=started enabled=yes