---
# file: roles/php-fpm/tasks/main.yml

- name: Install php-fpm
  yum: 
    name: "{{ packages }}" 
  vars:
    packages:
    - php
    - php-cli
    - php-fpm
    - php-devel
    - php-gd
    - php-mcrypt
    - php-enchant
    - php-IDNA_Convert
    - php-mbstring
    - php-pgsql
    - php-PHPMailer
    - php-process
    - php-simplepie
    - php-xml
    - php-zip
    - php-curl
    - php-pear
    - php-bcmath
    - php-json
    - php-pgsql 
    - php-pdo_pgsql
  tags: php-fpm

- name: Disable php-fpm default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm
  tags: php-fpm

- name: Configure php-fpm
  template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf
  notify:
    - restart php-fpm
  tags: php-fpm
