---
# file: roles/postgresql/handlers/main.yml
- name: restart postgresql-12
  service: name=postgresql-12 state=restarted enabled=yes

- name: reload postgresql-12
  service: name=postgresql-12 state=reloaded